/usr/bin/python readWWW.py unweighted_events_WWW_dim6_All_cW01.lhe test_unweighted_events_WWW_dim6_All_cW01.root
#/usr/bin/python readWWW.py unweighted_events_WWW_dim6_SM_cW01.lhe test_unweighted_events_WWW_dim6_SM_cW01.root
/usr/bin/python readWWW.py unweighted_events_WWW_dim6_Interference_cW01.lhe test_unweighted_events_WWW_dim6_Interference_cW01.root
/usr/bin/python readWWW.py unweighted_events_WWW_dim6_BSM_cW01.lhe test_unweighted_events_WWW_dim6_BSM_cW01.root
