/usr/bin/python readWWW.py unweighted_events_WWW_dim6_cHWB_All.lhe  test_unweighted_events_WWW_dim6_cHWB_All.root
/usr/bin/python readWWW.py unweighted_events_WWW_dim6_cHWB_BSM.lhe  test_unweighted_events_WWW_dim6_cHWB_BSM.root
/usr/bin/python readWWW.py unweighted_events_WWW_dim6_cHWB_Interference.lhe test_unweighted_events_WWW_dim6_cHWB_Interference.root

