/usr/bin/python readWWW.py cHWBLHEFiles/unweighted_events_WWW_dim6_cHWB_100000_Interference.lhe test_unweighted_events_WWW_dim6_cHWB_100000_Interference.root
/usr/bin/python readWWW.py cHWBLHEFiles/unweighted_events_WWW_dim6_cHWB_10_Interference.lhe test_unweighted_events_WWW_dim6_cHWB_10_Interference.root
/usr/bin/python readWWW.py cHWBLHEFiles/unweighted_events_WWW_dim6_cHWB_1_Interference.lhe test_unweighted_events_WWW_dim6_cHWB_1_Interference.root
/usr/bin/python readWWW.py cHWBLHEFiles/unweighted_events_WWW_dim6_cHWB_20_Interference.lhe test_unweighted_events_WWW_dim6_cHWB_20_Interference.root
/usr/bin/python readWWW.py cHWBLHEFiles/unweighted_events_WWW_dim6_cHWB_30_Interference.lhe test_unweighted_events_WWW_dim6_cHWB_30_Interference.root
/usr/bin/python readWWW.py cHWBLHEFiles/unweighted_events_WWW_dim6_cHWB_50_Interference.lhe test_unweighted_events_WWW_dim6_cHWB_50_Interference.root
