#/usr/bin/python readWWW.py unweighted_events_cW_01_DoubleInsertion.lhe test_unweighted_events_cW_01_DoubleInsertion.root
#/usr/bin/python readWWW.py unweighted_events_WWW_OnShell_BSM_DSC1.lhe test_unweighted_events_WWW_OnShell_BSM_DSC1_Comparison.root
#/usr/bin/python readWWW.py unweighted_events_cW_1_DoubleInsertion.lhe test_unweighted_events_cW_1_DoubleInsertion.root
#/usr/bin/python readWWW.py unweighted_events_WWW_OnShell_Interference_DSC1.lhe test_unweighted_events_WWW_OnShell_Interference_DSC1_Comparison.root
#/usr/bin/python readWWW.py unweighted_events_DoubleInsertion_WWW_Interference.lhe test_unweighted_events_DoubleInsertion_WWW_Interference.root
/usr/bin/python readWWW.py unweighted_events_WWW_dim6_cHWB_BSM_DoubleInsertion.lhe test_unweighted_events_WWW_dim6_cHWB_BSM_DoubleInsertion.root
