/usr/bin/python readWWW.py cHWBLHEFiles/unweighted_events_WWW_dim6_cHWB_100000_BSM.lhe test_unweighted_events_WWW_dim6_cHWB_100000_BSM.root
/usr/bin/python readWWW.py cHWBLHEFiles/unweighted_events_WWW_dim6_cHWB_10_BSM.lhe test_unweighted_events_WWW_dim6_cHWB_10_BSM.root
/usr/bin/python readWWW.py cHWBLHEFiles/unweighted_events_WWW_dim6_cHWB_1_BSM.lhe test_unweighted_events_WWW_dim6_cHWB_1_BSM.root
/usr/bin/python readWWW.py cHWBLHEFiles/unweighted_events_WWW_dim6_cHWB_20_BSM.lhe test_unweighted_events_WWW_dim6_cHWB_20_BSM.root
/usr/bin/python readWWW.py cHWBLHEFiles/unweighted_events_WWW_dim6_cHWB_30_BSM.lhe test_unweighted_events_WWW_dim6_cHWB_30_BSM.root
/usr/bin/python readWWW.py cHWBLHEFiles/unweighted_events_WWW_dim6_cHWB_50_BSM.lhe test_unweighted_events_WWW_dim6_cHWB_50_BSM.root
