#/usr/bin/python readWWW.py unweighted_events_WWW_dim6_cHd_All.lhe  test_unweighted_events_WWW_dim6_cHd_All.root
/usr/bin/python readWWW.py unweighted_events_WWW_dim6_cHd_1_BSM.lhe  test_unweighted_events_WWW_dim6_cHd_1_BSM.root
/usr/bin/python readWWW.py unweighted_events_WWW_dim6_cHd_1_Interference.lhe  test_unweighted_events_WWW_dim6_cHd_1_Interference.root

