/usr/bin/python readWWW.py unweighted_events_WWW_OnShell_All_DSC1.lhe test_unweighted_events_WWW_Onshell_All_DC1.root
/usr/bin/python readWWW.py unweighted_events_WWW_OnShell_Interference_DSC1.lhe test_unweighted_events_WWW_Onshell_Interference_DC1.root
/usr/bin/python readWWW.py unweighted_events_WWW_OnShell_BSM_DSC1.lhe test_unweighted_events_WWW_Onshell_BSM_DC1.root 
/usr/bin/python readWWW.py unweighted_events_WWW_OnShell_SM_DSC1.lhe test_unweighted_events_WWW_Onshell_SM_DC1.root 
