/usr/bin/python readWWW.py unweighted_events_WWW_dim6_All.lhe test_unweighted_events_WWW_dim6_All.root
/usr/bin/python readWWW.py unweighted_events_WWW_dim6_SM.lhe test_unweighted_events_WWW_dim6_SM.root
/usr/bin/python readWWW.py unweighted_events_WWW_dim6_Interference.lhe test_unweighted_events_WWW_dim6_Interference.root
/usr/bin/python readWWW.py unweighted_events_WWW_dim6_BSM.lhe test_unweighted_events_WWW_dim6_BSM.root

/usr/bin/python readWWW.py unweighted_events_WWW_dim6_All_cW01.lhe test_unweighted_events_WWW_dim6_All_cW01.root
/usr/bin/python readWWW.py unweighted_events_WWW_dim6_Interference_cW01.lhe test_unweighted_events_WWW_dim6_Interference_cW01.root
/usr/bin/python readWWW.py unweighted_events_WWW_dim6_BSM_cW01.lhe test_unweighted_events_WWW_dim6_BSM_cW01.root
