/usr/bin/python readWWW.py unweighted_events_WWW_dim6_cHWB_10_All.lhe  test_unweighted_events_WWW_dim6_cHWB_10_All.root
/usr/bin/python readWWW.py unweighted_events_WWW_dim6_cHWB_10_BSM.lhe  test_unweighted_events_WWW_dim6_cHWB_10_BSM.root
/usr/bin/python readWWW.py unweighted_events_WWW_dim6_cHWB_10_Interference.lhe test_unweighted_events_WWW_dim6_cHWB_10_Interference.root

